### ISSUE TITLE
Fix misspelling of info message "colcon acceleraction select"

### ISSUE THREAD

**Issue by tomasthoresen** [ros-acceleration/colcon-hardware-acceleration#12]
~/krs_ws$ colcon acceleration list
Firmware directory (/home/ros2/krs_ws/acceleration/firmware/select) not found.
_Select firmware first with "colcon **acceleraction** select ['kv260', 'zcu102']"._

"acceleraction" is not spelled right. The command returns an error message if copied and used from the info message.

**Comment by vmayoral** [comment]
Thanks @tomasthoresen! Do you mind sending a Pull Request fixing this?

**Comment by methylDragon** [comment]
This issue can be closed since the merge of https://github.com/ros-acceleration/colcon-hardware-acceleration/issues/12
